# Generated by Django 5.1.4 on 2024-12-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('nombre', 'parent')},
        ),
    ]
