# Generated by Django 5.1.4 on 2024-12-24 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('folders', '0002_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='categorias.categoria')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='folders.folder')),
                ('tags', models.ManyToManyField(blank=True, related_name='notas', to='tags.tag')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
